version: "3"

x-common-log-config: &default_config
  networks:
    - ice_lakehouse

x-common-healthcheck-default: &default_healthcheck
  timeout: 45s
  interval: 10s
  retries: 10
  start_period: 10s

services:
  # Spark Notebook Server
  notebook:
    build: ./docker/notebook
    container_name: notebook
    <<: *default_config
    volumes:
      - ./mnt/warehouse:/app/warehouse
      - ./mnt/notebooks:/app/notebooks
      - ./mnt/datasets:/app/datasets
    environment:

    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001


  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: minio
    env_file:
      - ./conf/.minio.conf
    <<: *default_config
    volumes:
      - minio_dev_vol:/data
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]


  nessie:
    image: projectnessie/nessie:0.67.0
    container_name: nessie
    <<: *default_config
    ports:
      - 19120:19120


  dremio:
    image: dremio/dremio-oss:24.1
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    volumes:
      - dremio_dev_vol:/opt/dremio/data
    <<: *default_config

  ################################################################################################################
  #####################################    SPARK SERVICES    #####################################################

  spark-master:
    build: ./docker/spark
    container_name: spark-master
    <<: *default_config
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_METRICS_MASTER_ENABLED=true
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '18080:8080'
    healthcheck:
      test: [ "CMD", "ls" ]
      <<: *default_healthcheck

  spark-worker:
    build: ./docker/spark
    <<: *default_config
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    healthcheck:
      test: [ "CMD", "ls" ]
      <<: *default_healthcheck

volumes:
  minio_dev_vol:
  dremio_dev_vol:

networks:
  ice_lakehouse:
    name: ice_lakehouse